### ISSUE TITLE
Bug with too much Money

### ISSUE THREAD

**Issue by MonoAdrian23** [lt-name/MoneyRanking#1]
When a Player have too much Money, Numbers are replaced by Letters.
![Screenshot_2021-11-02-11-33-22-78_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/59027482/139831262-9dbc8cc5-3860-4ef7-97cb-b8df4e6a9b7f.jpg)

**Comment by lt-name** [comment]
This is a problem with the RankingAPI plugin, Please update to 1.4.3
Latest build: https://ci.lt-name.cn/job/RankingAPI/

**Comment by MonoAdrian23** [comment]
It works now, thank you very much!
